spring:
  config:
    activate:
      on-profile: real
  ### DB 설정 ###
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  #  datasource:
  #    url: jdbc:mysql://호스트이름:3306/board?serverTimezone=UTC&characterEncoding=UTF-8

  ### JPA 설정 ###
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

---

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  ### H2 DataBase ###
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  ### JPA 설정 ###
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
      show-sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  ### DB 설정 ###
  datasource:
    url: jdbc:h2:mem:odds_and_ends
    driver-class-name: org.h2.Driver
    username: sa

jwt:
  secret: ${SECRET}

cloud:
  aws:
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${BUCKET_NAME}